# MySQL. Versions 5.1.10 and up are supported.
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  password: <%= ENV['MYSQL_DEV_PASS'] %>
  database: ssl-barth_dev

test:
  <<: *default
  database: ssl-barth_test

production:
  <<: *default
  password: <%= ENV['MYSQL_PRODUCTION_PASS'] %>
  database: sslbarth_production
  host: <%= ENV['MYSQL_PRIDUCTION_HOST'] %>

